version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests
  build:
    commands:
      - echo "Packaging Spring Boot application..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Copying JAR file to the artifact directory..."
      - cp target/*.jar build/
      -
artifacts:
  files:
    - build/*.jar
