version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn clean install
#  post_build:
#    commands:
#      - cp -r .ebextensions/ target/ROOT/
#      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml

#artifacts:
#  files:
#    - template-export.yml
#    - template-configuration.json
